### ISSUE TITLE
goomba conversion to ida 7.7 error

### ISSUE THREAD

**Issue by botao1995** [HexRaysSA/goomba#10]
Hi friend,
I am studying MBA recently, it is a great honor to read your article.
I don't have the latest ida v8.2.
Would like to consider porting this plugin to ida v7.7.
I encountered the following errors, and I don't know how to translate these error codes.
![1679620618911](https://user-images.githubusercontent.com/47848566/227399792-6f39e84a-27fb-4457-a065-0a59146332de.png)

**Comment by skochinsky** [comment]
Sorry, no plans for this

**Comment by 0x410c** [comment]
https://github.com/0x410c/goomba75
