### ISSUE TITLE
Does goomba plugin support IDA 8.2 freeware version?  (No errors during installation)

### ISSUE THREAD

**Issue by uniquadev** [HexRaysSA/goomba#11]
Hello,

I am interested in using goomba, but I need to know if it is compatible with the freeware version of IDA 8.2. I have searched through the documentation and the issues on this repository, but I could not find any information about this.

 I installed the plugin and didn't receive any errors during the installation process nor in ida console.

Can you please confirm if this plugin is compatible with IDA 8.2 freeware version or not? If it is not compatible, are there any plans to make it compatible in the near future?

Thank you in advance for your help.

**Comment by skochinsky** [comment]
Goomba does not work with the cloud decompiler of IDA Free; it needs the full, offline decompiler. No plans for supporting it either.
