### ISSUE TITLE
LoadLibrary(....\plugins\goomba64.dll) error: 找不到指定的程序

### ISSUE THREAD

**Issue by 0xsyj** [HexRaysSA/goomba#13]
The full error is: LoadLibrary(C:\Tool\IDA76\IDAPro7.6\plugins\goomba64.dll) error: 找不到指定的程序
But the path has no Chinese and does not contain spaces， i don't know why.

After downloading goomba-win, place goomba.dll and goomba64.dll in the plugins directory, and libz3.dll in the same directory as ida.exe、ida64.exe.

**Comment by aundro** [comment]
Hi,

I'm afraid goomba is only going to work with IDA 8.2+
