### ISSUE TITLE
goomba on mba_challenge returns wrong result

### ISSUE THREAD

**Issue by pgarba** [HexRaysSA/goomba#6]
When you apply goomba on "mba_challenge.i64" it returns "4*x+4*y+2*z" as simplification.
This seems to be wrong.

```

TestVector = [94 28 183]

MBA = "2 * (((y + (z & ~y)  + (z & ~y + (z & ~y) )) & ~z)+ (z | ~x) + x + z + 1 + (y + (z & ~y)  & y) + (((y ^ x) + 2 * (y & x)) ^ x) + (z & ~((z | ~x) + x + 1)) + 2 * (((y ^ x) + 2 * (y & x)) & x) - ((y + (z & ~y)  + (z & ~y + (z & ~y) )) | y + (z & ~y) ))"

Return = 70

SimpMBA = "4*x+4*y+2*z"

Return = 86
```

https://godbolt.org/z/1dv4fcTvv

SiMBA has the same problem btw but detects the Simplified MBA as not valid.

**Comment by skochinsky** [comment]
Which function from the binary is that? Did Z3 proof succeed or time out? If the latter, did you try increasing the timeout?

**Comment by skochinsky** [comment]
@pgarba Are you sure your counterexample is correct? I get 854 for both expressions for the provided values.

**Comment by skochinsky** [comment]
Okay, I think I see the problem. Your `MBA` expression is not what gets simplified by gooMBA. Here's the initial expression from the decompiler:

```
  unsigned int v3; // r8d@1 12A9 TYPED

  v3 = y + (z & ~y);
  return 2
       * (((v3 + (z & ~v3)) & ~z)
        + (z | ~x)
        + x
        + z
        + 1
        + (v3 & y)
        + (((y ^ x) + 2 * (y & x)) ^ x)
        + (z & ~((z | ~x) + x + 1))
        + 2 * (((y ^ x) + 2 * (y & x)) & x)
        - ((v3 + (z & ~v3)) | v3));
```

After substitution it becomes:

2* (((y + (z & ~y) + (z & ~(y + (z & ~y)))) & ~z) + (z | ~x) + x + z + 1 + ((y + (z & ~y)) & y) + (((y ^ x) + 2 * (y & x)) ^ x) + (z & ~((z | ~x) + x + 1)) + 2 * (((y ^ x) + 2 * (y & x)) & x)- (((y + (z & ~y)) + (z & ~(y + (z & ~y)))) | (y + (z & ~y))));

Note the extra parens around the expression to the right of the last `|`.

**Comment by pgarba** [comment]
thanks for clarification.
