### ISSUE TITLE
Windows release version contains debug DLL dependencies

### ISSUE THREAD

**Issue by adamprescott91** [HexRaysSA/goomba#8]
The https://github.com/HexRaysSA/goomba/releases/tag/v8.2.230125 goomba-win.zip release contains goomba plugin DLLs that have dependencies on:

MSVCP140D.dll
VCRUNTIME140D.dll
VCRUNTIME140_1D.dll
ucrtbased.dll

These are all debug versions of the VC redistributable DLLs and not the release versions.
Further the VCRUNTIME140_1D.dll does not seem to be available in some versions of visual studio and so cannot be copied locally if the end user has a copy of visual studio.

The files should be rebuilt in release mode rather than debug mode so that the VC redistributable files contain the correct DLLs for them.

**Comment by skochinsky** [comment]
Thank you, we've updated the build to use the release DLLs
