### ISSUE TITLE
can't load file  error

### ISSUE THREAD

**Issue by IMMORTAL23** [HexRaysSA/goomba#9]
When ida initial, it throw the error: 
LoadLibrary(D:\softwares\reverse_tools\ida7_7\ida7_7\plugins\goomba64.dll) error: The specified module could not be found.
D:\softwares\reverse_tools\ida7_7\ida7_7\plugins\goomba64.dll: can't load file 
LoadLibrary(D:\softwares\reverse_tools\ida7.7\ida7.7\plugins\goomba64.dll) error: The specified module could not be found.
D:\softwares\reverse_tools\ida7.7\ida7.7\plugins\goomba64.dll: can't load file

HexRaysCodeXplorer plugin by @REhints loaded.

[+] plugin init
[+] plugin term

But I do have the file in the above path.  Do i need a ida with version >= 8.0 ?

**Comment by skochinsky** [comment]
goomba requires IDA 8.2
